# Generated by Django 4.1 on 2022-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
            ],
        ),
    ]
